CREATE TABLE [wed].[Hotel]
(
	[HotelId] INT IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
	[Name] NVARCHAR(100) NOT NULL,
	[Website] NVARCHAR(256) NOT NULL,
	[Number] NVARCHAR(50) NOT NULL,
	[Address] NVARCHAR(MAX) NOT NULL,
	[Image] NVARCHAR(256) NOT NULL,
	[Latitude] DECIMAL(18, 6) NOT NULL,
	[Longitude] DECIMAL(18, 6) NOT NULL,
	CONSTRAINT [PK_Hotel] PRIMARY KEY CLUSTERED ([HotelId] ASC),
)
