//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaType
    {
        public AreaType()
        {
            this.Gadget2Role2AreaType = new HashSet<Gadget2Role2AreaType>();
        }
    
        public int AreaTypeId { get; set; }
        public System.Guid AreaTypeUid { get; set; }
        public string AreaType1 { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Gadget2Role2AreaType> Gadget2Role2AreaType { get; set; }
    }
}
