//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public Article()
        {
            this.ArticleComments = new HashSet<ArticleComment>();
            this.ArticleContents = new HashSet<ArticleContent>();
            this.ArticleImages = new HashSet<ArticleImage>();
            this.Bulletins = new HashSet<Bulletin>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int ArticleId { get; set; }
        public System.Guid ArticleUid { get; set; }
        public int ArticleTypeId { get; set; }
        public int SiteId { get; set; }
        public int Status { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        public virtual Category Category { get; set; }
        public virtual Site Site { get; set; }
        public virtual ICollection<ArticleComment> ArticleComments { get; set; }
        public virtual ICollection<ArticleContent> ArticleContents { get; set; }
        public virtual ICollection<ArticleImage> ArticleImages { get; set; }
        public virtual ICollection<Bulletin> Bulletins { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
