//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleContent
    {
        public int ArticleContentId { get; set; }
        public System.Guid ArticleContentUid { get; set; }
        public int ArticleId { get; set; }
        public string Content { get; set; }
        public int Version { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
