//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    
    public partial class ArticleInfo
    {
        public int ArticleId { get; set; }
        public System.Guid ArticleUid { get; set; }
        public int Status { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string CategoryImage { get; set; }
        public System.DateTime Date { get; set; }
        public string TypeName { get; set; }
        public int ArticleTypeId { get; set; }
        public int Version { get; set; }
        public string Title { get; set; }
        public Nullable<bool> HasImages { get; set; }
        public string ImageThumbnail { get; set; }
    }
}
