//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleImage
    {
        public int ArticleImageId { get; set; }
        public System.Guid ArticleImageUid { get; set; }
        public int ArticleId { get; set; }
        public string Image { get; set; }
        public string Thumbnail { get; set; }
        public string Position { get; set; }
        public string Size { get; set; }
    
        public virtual Article Article { get; set; }
    }
}
