//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticleComment
    {
        public ArticleComment()
        {
            this.ArticleComment1 = new HashSet<ArticleComment>();
        }
    
        public int ArticleCommentId { get; set; }
        public System.Guid ArticleCommentUid { get; set; }
        public int ArticleId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> GuestId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ParentCommentId { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual ICollection<ArticleComment> ArticleComment1 { get; set; }
        public virtual ArticleComment ArticleComment2 { get; set; }
        public virtual Guest Guest { get; set; }
        public virtual User User { get; set; }
    }
}
