//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    
    public partial class BrowserStat
    {
        public string UserAgent { get; set; }
        public string BrowserName { get; set; }
        public string BrowserVersion { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
