//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bulletin
    {
        public Bulletin()
        {
            this.BulletinContents = new HashSet<BulletinContent>();
        }
    
        public int BulletinId { get; set; }
        public System.Guid BulletinUid { get; set; }
        public Nullable<int> ArticleId { get; set; }
        public Nullable<int> GalleryId { get; set; }
        public int BulletinTypeId { get; set; }
        public int SiteId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual BulletinType BulletinType { get; set; }
        public virtual Article Article { get; set; }
        public virtual Gallery Gallery { get; set; }
        public virtual Site Site { get; set; }
        public virtual ICollection<BulletinContent> BulletinContents { get; set; }
    }
}
