//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulletinType
    {
        public BulletinType()
        {
            this.Bulletins = new HashSet<Bulletin>();
        }
    
        public int BulletinTypeId { get; set; }
        public System.Guid BulletinTypeUid { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Class { get; set; }
        public string Assembly { get; set; }
    
        public virtual ICollection<Bulletin> Bulletins { get; set; }
    }
}
