//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BulletinContent
    {
        public int BulletinContentId { get; set; }
        public System.Guid BulletinContentUid { get; set; }
        public int BulletinId { get; set; }
        public string Content { get; set; }
    
        public virtual Bulletin Bulletin { get; set; }
    }
}
