//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    
    public partial class CategoryInfo
    {
        public string CategoryName { get; set; }
        public string FullCategoryName { get; set; }
        public string CategoryDescription { get; set; }
        public string ParentDescription { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> ParentCategoryId { get; set; }
        public string ImageName { get; set; }
    }
}
