//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public ContactInfo()
        {
            this.Addresses = new HashSet<Address>();
            this.Emails = new HashSet<Email>();
            this.PhoneNumbers = new HashSet<PhoneNumber>();
        }
    
        public int ContactInfoId { get; set; }
        public System.Guid ContactInfoUid { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int CountryId { get; set; }
        public string City { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual ICollection<PhoneNumber> PhoneNumbers { get; set; }
    }
}
