//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactForm
    {
        public int ContactFormId { get; set; }
        public System.Guid ContactFormUid { get; set; }
        public int SiteId { get; set; }
        public string Title { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Content { get; set; }
        public System.DateTime Date { get; set; }
        public bool Read { get; set; }
        public bool Public { get; set; }
    
        public virtual Site Site { get; set; }
    }
}
