//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Addresses = new HashSet<Address>();
        }
    
        public int CountryId { get; set; }
        public System.Guid CountryUid { get; set; }
        public string Name { get; set; }
        public string ISO3166 { get; set; }
        public string ImageName { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
    }
}
