//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int EmailId { get; set; }
        public System.Guid EmailUid { get; set; }
        public int ContactInfoId { get; set; }
        public string Address { get; set; }
        public bool IsPrimary { get; set; }
    
        public virtual ContactInfo ContactInfo { get; set; }
    }
}
