//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventLog
    {
        public int EventLogId { get; set; }
        public System.Guid EventLogUid { get; set; }
        public byte EventType { get; set; }
        public string EventSource { get; set; }
        public string Description { get; set; }
        public int EventId { get; set; }
    }
}
