//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gadget2Role2AreaType
    {
        public int GadgetId { get; set; }
        public int RoleId { get; set; }
        public int AreaTypeId { get; set; }
    
        public virtual Gadget Gadget { get; set; }
        public virtual AreaType AreaType { get; set; }
        public virtual Role Role { get; set; }
    }
}
