//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gallery
    {
        public Gallery()
        {
            this.Bulletins = new HashSet<Bulletin>();
            this.GalleryImages = new HashSet<GalleryImage>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int GalleryId { get; set; }
        public System.Guid GalleryUid { get; set; }
        public string Title { get; set; }
        public int CreatedByUserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CategoryId { get; set; }
    
        public virtual ICollection<Bulletin> Bulletins { get; set; }
        public virtual Category Category { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<GalleryImage> GalleryImages { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
