//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest
    {
        public Guest()
        {
            this.ArticleComments = new HashSet<ArticleComment>();
        }
    
        public int GuestId { get; set; }
        public System.Guid GuestUid { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsArchived { get; set; }
    
        public virtual ICollection<ArticleComment> ArticleComments { get; set; }
    }
}
