//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuestGroup
    {
        public GuestGroup()
        {
            this.Guest1 = new HashSet<Guest1>();
        }
    
        public int GuestGroupId { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
    
        public virtual ICollection<Guest1> Guest1 { get; set; }
    }
}
