//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guest1
    {
        public Guest1()
        {
            this.FoodChoices = new HashSet<FoodChoice>();
        }
    
        public int GuestId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public byte GuestType { get; set; }
        public byte GuestSide { get; set; }
        public bool InvitationSent { get; set; }
        public string Code { get; set; }
        public Nullable<bool> Attending { get; set; }
        public Nullable<int> GuestGroupId { get; set; }
        public string DietaryRequirements { get; set; }
        public Nullable<System.DateTime> RSVPDate { get; set; }
        public string RSVPIpAddress { get; set; }
    
        public virtual ICollection<FoodChoice> FoodChoices { get; set; }
        public virtual GuestGroup GuestGroup { get; set; }
    }
}
