//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageVisit
    {
        public PageVisit()
        {
            this.PageVisit1 = new HashSet<PageVisit>();
        }
    
        public int Id { get; set; }
        public byte AreaType { get; set; }
        public Nullable<int> ItemId { get; set; }
        public string SearchTerm { get; set; }
        public string Referer { get; set; }
        public string Url { get; set; }
        public string LinkType { get; set; }
        public Nullable<int> PreviousId { get; set; }
        public string UserAgent { get; set; }
        public string UserLanguages { get; set; }
        public string BrowserVersion { get; set; }
        public string BrowserName { get; set; }
        public string IpAddress { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual ICollection<PageVisit> PageVisit1 { get; set; }
        public virtual PageVisit PageVisit2 { get; set; }
    }
}
