//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumber
    {
        public int PhoneNumberId { get; set; }
        public System.Guid PhoneNumberUid { get; set; }
        public int ContactInfoId { get; set; }
        public string Number { get; set; }
        public int Type { get; set; }
    
        public virtual ContactInfo ContactInfo { get; set; }
    }
}
