//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating2ArticleType2Category
    {
        public int RatingId { get; set; }
        public int ArticleTypeId { get; set; }
        public int CategoryId { get; set; }
        public int Ordinal { get; set; }
    
        public virtual ArticleType ArticleType { get; set; }
        public virtual Rating Rating { get; set; }
        public virtual Category Category { get; set; }
    }
}
