//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public Rating()
        {
            this.Rating2ArticleType2Category = new HashSet<Rating2ArticleType2Category>();
        }
    
        public int RatingId { get; set; }
        public System.Guid RatingUid { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Rating2ArticleType2Category> Rating2ArticleType2Category { get; set; }
    }
}
