//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.Gadgets = new HashSet<Gadget>();
            this.Articles = new HashSet<Article>();
            this.Bulletins = new HashSet<Bulletin>();
            this.ContactForms = new HashSet<ContactForm>();
            this.Users = new HashSet<User>();
        }
    
        public int SiteId { get; set; }
        public System.Guid SiteUid { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string Host { get; set; }
    
        public virtual ICollection<Gadget> Gadgets { get; set; }
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Bulletin> Bulletins { get; set; }
        public virtual ICollection<ContactForm> ContactForms { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
