//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    
    public partial class SnapshotLite
    {
        public int SnapshotId { get; set; }
        public string Url { get; set; }
        public System.DateTime Date { get; set; }
    }
}
