//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaticRoute
    {
        public string StaticRoute1 { get; set; }
        public string Area { get; set; }
        public string Action { get; set; }
        public int Id { get; set; }
    }
}
