//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.Articles = new HashSet<Article>();
            this.Galleries = new HashSet<Gallery>();
        }
    
        public int TagId { get; set; }
        public System.Guid TagUid { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
        public virtual ICollection<Gallery> Galleries { get; set; }
    }
}
