//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TooksCms.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ArticleComments = new HashSet<ArticleComment>();
            this.Galleries = new HashSet<Gallery>();
            this.ContactInfoes = new HashSet<ContactInfo>();
            this.Roles = new HashSet<Role>();
        }
    
        public int UserId { get; set; }
        public System.Guid UserUid { get; set; }
        public string LoginName { get; set; }
        public string ScreenName { get; set; }
        public int SiteId { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreationIP { get; set; }
        public System.DateTime LastLogin { get; set; }
        public string LastLoginIP { get; set; }
    
        public virtual ICollection<ArticleComment> ArticleComments { get; set; }
        public virtual ICollection<Gallery> Galleries { get; set; }
        public virtual Site Site { get; set; }
        public virtual ICollection<ContactInfo> ContactInfoes { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
    }
}
