define('models', [
    'models/bulletin',
    'models/article',
    'models/tag',
    'models/gallery',
    'models/comment',
    'models/contact',
    'models/listItem',
    'models/lookup',
    'models/route',
    'models/gadget',
    'models/rating',
    'models/stats'],
    function (
        bulletin,
        article,
        tag,
        gallery,
        comment,
        contact,
        listItem,
        lookup,
        route,
        gadget,
        rating,
        stats) {
        "use strict";
        return {
            NewsBulletin: bulletin.newsBulletin,
            ReviewBulletin: bulletin.reviewBulletin,
            GalleryBulletin: bulletin.galleryBulletin,
            ReviewArticle: article.reviewArticle,
            NewsArticle: article.newsArticle,
            ArticleInfo: article.articleInfo,
            Tag: tag.tag,
            RankedTag: tag.rankedTag,
            Gallery: gallery.gallery,
            GalleryInfo: gallery.galleryInfo,
            GalleryListItem: gallery.galleryListItem,
            Comment: comment.comment,
            ContactForm: contact.contactForm,
            ListItem: listItem.listItem,
            ImageListItem: listItem.imageListItem,
            Country: lookup.country,
            Category: lookup.category,
            Route: route.route,
            Gadget: gadget.gadget,
            Rating: rating.rating,
            RatingLink: rating.ratingLink,
            BrowserStat: stats.browserStat,
            PageVisit: stats.pageVisit,
            ClickStat: stats.clickStat
        };
    });